version: '3.4'
services:
  database:
    image: 'mongo'
    container_name: 'parking-deb-mongo'
    environment:
      - MONGO_INIT_DATABASE=parking_db
      - MONGO_INIT_ROOT_USERNAME=parking-app
      - MONGO_INIT_ROOT_PASSWORD=parking-app
    volumes:
      - ./init-mongo.json:/docker-entrypoint-initdb.d/init-mongo.json:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    network_mode: host
volumes:
  mongodb_data_volume:
    external: true